source 'https://rubygems.org'
group :jekyll_plugins do
    gem 'jekyll', '4.3.2'
    gem 'addressable', '2.8.1'
    gem 'colorator', '1.1.0'
    gem 'em-websocket', '0.5.3'
    gem 'i18n', '1.12.0'
    gem 'jekyll-sass-converter', '3.0.0'
    gem 'jekyll-watch', '2.2.1'
    gem 'kramdown', '2.4.0'
    gem 'kramdown-parser-gfm', '1.1.0'
    gem 'liquid', '4.0.4'
    gem 'mercenary', '0.4.0'
    gem 'pathutil', '0.16.2'
    gem 'rouge', '4.0.1'
    gem 'safe_yaml', '1.0.5'
    gem 'terminal-table', '3.0.2'
    gem 'unicode-display_width', '2.4.2'
    gem 'webrick', '1.7.0'
    
    gem 'listen', '3.8.0'
    gem 'concurrent-ruby', '1.2.0'
    gem 'rexml', '3.2.5'

    gem 'jekyll-archives', '2.2.1'
    gem 'jekyll-diagrams', '0.10.0'
    gem 'jekyll-email-protect', '1.1.0'
    gem 'jekyll-feed', '0.17.0'
    gem 'jekyll-imagemagick', '1.4.0'
    gem 'jekyll-minifier', '0.1.10'

    gem 'public_suffix'
    gem 'htmlcompressor'
    gem 'namae'
    gem 'jekyll-link-attributes'
    gem 'jekyll-twitter-plugin'
    gem 'gemoji'
    gem 'mini_racer'
    gem 'unicode_utils'
    gem 'jekyll-paginate-v2'
    gem 'latex-decode'
    gem 'jekyll-scholar'
    gem 'jekyll-sitemap'
    gem 'jemoji'
end
group :other_plugins do
    gem 'multi_xml', '0.6.0'
    gem 'httparty', '0.21.0'
    gem 'sax-machine', '1.3.2' 
    gem 'feedjira', '3.2.2'
end
